# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: 'Apigee'
  demands: 'npm'


steps:
- checkout: none

- script: |
    cd /home/admin/TestSamples/pipelines-javascript-master
    pwd
    ./run_ci_tests.sh > run_ci_tests_output.txt
  displayName: 'run CI testing.'
